# -*- coding: utf-8 -*-
"""Restauração de Imagens Antigas V2 - PDI_DesafioFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w61aMPT7pwW2RP25TXssvfM-CD1oM6Am

# Dataset
"""

# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("marcinrutecki/old-photos")

# print("Path to dataset files:", path)

"""# Pipeline Principal"""

import cv2
import numpy as np
from skimage import exposure, restoration, filters, morphology
from skimage.util import img_as_float, img_as_ubyte
from matplotlib import pyplot as plt
from scipy import ndimage, fft
import warnings

warnings.filterwarnings('ignore')

def plot_comparison(original, processed, title_processed, figsize=(15, 10)):
    plt.figure(figsize=figsize)

    # Subplot para a imagem original (1 linha, 2 colunas, posição 1)
    plt.subplot(1, 2, 1)
    if len(original.shape) == 2:
        plt.imshow(original, cmap='gray')
    else:
        if original.dtype == np.float64:
            original_display = (original * 255).clip(0, 255).astype(np.uint8)
            plt.imshow(cv2.cvtColor(original_display, cv2.COLOR_BGR2RGB))
        else:
            plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    # Subplot para a imagem processada (1 linha, 2 colunas, posição 2)
    plt.subplot(1, 2, 2)
    if len(processed.shape) == 2:
        plt.imshow(processed, cmap='gray')
    else:
        if processed.dtype == np.float64:
            processed_display = (processed * 255).clip(0, 255).astype(np.uint8)
            plt.imshow(cv2.cvtColor(processed_display, cv2.COLOR_BGR2RGB))
        else:
            plt.imshow(cv2.cvtColor(processed, cv2.COLOR_BGR2RGB))
    plt.title(title_processed)
    plt.axis('off')

    plt.tight_layout()  # Ajusta o espaçamento entre as imagens
    plt.show()

def preprocess_image(img, target_size=None, align=False):

    # Garantir que a imagem está no formato correto
    if img.dtype == np.float64:
        img = (img * 255).clip(0, 255).astype(np.uint8)

    # Converter para float32 para operações posteriores
    processed = img_as_float(img)

    # Converter para tons de cinza para operações de alinhamento
    if len(processed.shape) == 3 and processed.shape[2] == 3:
        gray = cv2.cvtColor((processed * 255).astype(np.uint8), cv2.COLOR_BGR2GRAY)
        gray = img_as_float(gray)
    else:
        gray = processed.copy()

    # Alinhamento automático
    if align:
        try:
            edges = cv2.Canny((gray * 255).astype(np.uint8), 50, 150, apertureSize=3)
            lines = cv2.HoughLinesP(edges, 1, np.pi/180, 100, minLineLength=100, maxLineGap=10)

            angles = []
            for line in lines:
                x1, y1, x2, y2 = line[0]
                angle = np.arctan2(y2 - y1, x2 - x1) * 180 / np.pi
                angles.append(angle)

            median_angle = np.median(angles)
            if np.abs(median_angle) > 0.5:
                rows, cols = gray.shape[:2]
                M = cv2.getRotationMatrix2D((cols/2, rows/2), median_angle, 1)
                gray = cv2.warpAffine(gray, M, (cols, rows), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)
                if len(processed.shape) == 3:
                    for i in range(3):
                        processed[:, :, i] = cv2.warpAffine(processed[:, :, i], M, (cols, rows), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)
        except Exception as e:
            print(f"Alinhamento automático falhou: {e} - continuando sem alinhamento")

    # Redimensionamento
    if target_size is not None:
        h, w = gray.shape[:2]
        target_w, target_h = target_size

        if target_w is None:
            target_w = int(w * (target_h / h))
        if target_h is None:
            target_h = int(h * (target_w / w))

        gray = cv2.resize(gray, (target_w, target_h), interpolation=cv2.INTER_AREA)
        if len(processed.shape) == 3:
            processed = cv2.resize(processed, (target_w, target_h), interpolation=cv2.INTER_AREA)

    # Normalização de contraste
    if len(processed.shape) == 3:
        for i in range(3):
            processed[:, :, i] = exposure.rescale_intensity(processed[:, :, i])
    else:
        processed = exposure.rescale_intensity(processed)

    plot_comparison(img, processed, 'Pré-processamento')
    return processed

def remove_noise_artifacts(img, bilateral_d=0, bilateral_sigma_color=0, bilateral_sigma_space=0,
                         median_k=0, inpaint_radius=0, fft_threshold=0):
    processed = img.copy()

    # Converter para uint8 se necessário (mantendo original para retorno)
    if processed.dtype == np.float64:
        processed_uint8 = (processed * 255).clip(0, 255).astype(np.uint8)
    else:
        processed_uint8 = (processed * 255).clip(0, 255).astype(np.uint8) if processed.max() <= 1.0 else processed.astype(np.uint8)

    # 1. Filtro bilateral (apenas se parâmetros > 0)
    if bilateral_d > 0 and bilateral_sigma_color > 0 and bilateral_sigma_space > 0:
        if len(processed.shape) == 3:
            processed = cv2.bilateralFilter(processed_uint8, bilateral_d, bilateral_sigma_color, bilateral_sigma_space)
        else:
            processed = cv2.bilateralFilter(processed_uint8, bilateral_d, bilateral_sigma_color, bilateral_sigma_space)
        processed = img_as_float(processed)

    # 2. Filtro mediano (apenas se kernel > 0)
    if median_k > 0:
        median_k = max(3, median_k | 1)  # Garantir ímpar e ≥3
        processed = cv2.medianBlur(processed_uint8, median_k)
        processed = img_as_float(processed)

    # 3. Inpainting (apenas se raio > 0)
    if inpaint_radius > 0:
        gray = cv2.cvtColor(processed_uint8, cv2.COLOR_BGR2GRAY) if len(processed.shape) == 3 else processed_uint8
        edges = cv2.Canny(gray, 50, 150)
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
        edges = cv2.dilate(edges, kernel, iterations=1)

        if np.sum(edges) > 100:
            if len(processed.shape) == 3:
                inpainted = np.zeros_like(processed_uint8)
                for i in range(3):
                    inpainted[:, :, i] = cv2.inpaint(processed_uint8[:, :, i], edges, inpaint_radius, cv2.INPAINT_TELEA)
                processed = img_as_float(inpainted)
            else:
                processed = img_as_float(cv2.inpaint(processed_uint8, edges, inpaint_radius, cv2.INPAINT_TELEA))

    # 4. Filtragem FFT (apenas se threshold > 0)
    if fft_threshold > 0:
        if len(processed.shape) == 3:
            fft_img = np.zeros_like(processed, dtype=np.float32)
            for i in range(3):
                channel = processed[:, :, i].astype(np.float32)
                fft_channel = np.fft.fft2(channel)
                fft_shifted = np.fft.fftshift(fft_channel)

                rows, cols = channel.shape
                crow, ccol = rows // 2, cols // 2
                mask = np.ones((rows, cols), np.float32)
                radius = int(min(rows, cols) * fft_threshold)
                mask[crow-radius:crow+radius, ccol-radius:ccol+radius] = 0

                fft_shifted *= mask
                fft_ishifted = np.fft.ifftshift(fft_shifted)
                img_back = np.abs(np.fft.ifft2(fft_ishifted))
                fft_img[:, :, i] = exposure.rescale_intensity(img_back)
            processed = fft_img
        else:
            channel = processed.astype(np.float32)
            fft_img = np.fft.fft2(channel)
            fft_shifted = np.fft.fftshift(fft_img)

            rows, cols = channel.shape
            crow, ccol = rows // 2, cols // 2
            mask = np.ones((rows, cols), np.float32)
            radius = int(min(rows, cols) * fft_threshold)
            mask[crow-radius:crow+radius, ccol-radius:ccol+radius] = 0

            fft_shifted *= mask
            fft_ishifted = np.fft.ifftshift(fft_shifted)
            img_back = np.abs(np.fft.ifft2(fft_ishifted))
            processed = exposure.rescale_intensity(img_back)

    plot_comparison(img, processed, 'Remoção de Ruído e Artefatos')
    return processed

def deblur_image(img, psf_type='circular', psf_size=15, psf_angle=0, wiener_balance=0.01):

    processed = img.copy()

    # Criar PSF (Point Spread Function)
    if psf_type == 'circular':
        psf = np.zeros((psf_size, psf_size))
        psf[psf_size//2, psf_size//2] = 1
        psf = filters.gaussian(psf, sigma=psf_size/4)
    elif psf_type == 'linear':
        psf = np.zeros((psf_size, psf_size))
        angle_rad = np.deg2rad(psf_angle)
        x_center, y_center = (psf_size - 1) // 2, (psf_size - 1) // 2

        # Desenhar linha no PSF
        x_end = x_center + int((psf_size/2) * np.cos(angle_rad))
        y_end = y_center + int((psf_size/2) * np.sin(angle_rad))
        cv2.line(psf, (x_center, y_center), (x_end, y_end), 1, thickness=1)
        psf /= psf.sum()

    # Aplicar deconvolução para cada canal (se colorido)
    if len(processed.shape) == 3:
        deblurred = np.zeros_like(processed)
        for i in range(3):
            channel = processed[:, :, i]
            deblurred[:, :, i] = restoration.wiener(channel, psf, wiener_balance)
        processed = exposure.rescale_intensity(deblurred)
    else:
        processed = restoration.wiener(processed, psf, wiener_balance)
        processed = exposure.rescale_intensity(processed)

    plot_comparison(img, processed, 'Redução de Blur')
    return processed

def enhance_details(img, clahe_clip_limit=2.0, clahe_grid_size=(8, 8),
                   unsharp_amount=1.5, unsharp_sigma=1.0, sobel_kernel=3):

    processed = img.copy()

    # Garantir dtype correto para cvtColor
    if processed.dtype == np.float64:
        processed = (processed * 255).clip(0, 255).astype(np.uint8)

    # Converter para tons de cinza para algumas operações
    if len(processed.shape) == 3 and processed.shape[2] == 3:
        gray = cv2.cvtColor(processed, cv2.COLOR_BGR2GRAY)
    else:
        gray = processed.copy()

    # 1. Equalização de histograma adaptativa (CLAHE)
    if len(processed.shape) == 3:
        lab = cv2.cvtColor((processed * 255).astype(np.uint8), cv2.COLOR_BGR2LAB)
        l, a, b = cv2.split(lab)

        clahe = cv2.createCLAHE(clipLimit=clahe_clip_limit, tileGridSize=clahe_grid_size)
        l = clahe.apply(l)

        lab = cv2.merge((l, a, b))
        processed = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR) / 255.0
    else:
        clahe = cv2.createCLAHE(clipLimit=clahe_clip_limit, tileGridSize=clahe_grid_size)
        processed = clahe.apply((processed * 255).astype(np.uint8)) / 255.0

    # 2. Unsharp masking
    blurred = cv2.GaussianBlur(processed, (0, 0), unsharp_sigma)
    processed = cv2.addWeighted(processed, 1.0 + unsharp_amount, blurred, -unsharp_amount, 0)

    # 3. Realce de bordas com Sobel (apenas para visualização, não aplicado diretamente)
    sobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=sobel_kernel)
    sobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=sobel_kernel)
    sobel = np.sqrt(sobelx**2 + sobely**2)
    sobel = exposure.rescale_intensity(sobel)

    # Combinar suavemente o realce de bordas
    if len(processed.shape) == 3:
        for i in range(3):
            processed[:, :, i] = np.clip(processed[:, :, i] + 0.1 * sobel, 0, 1)
    else:
        processed = np.clip(processed + 0.1 * sobel, 0, 1)

    plot_comparison(img, processed, 'Realce de Detalhes')
    return processed

def color_correction(img, white_balance=False, saturation_factor=1.0,
                    contrast_alpha=1.0, contrast_beta=0):
    processed = img.copy()

    # Converter para uint8 para operações OpenCV
    if processed.max() <= 1.0:
        processed_uint8 = (processed * 255).clip(0, 255).astype(np.uint8)
    else:
        processed_uint8 = processed.astype(np.uint8)

    if len(processed.shape) == 3 and processed.shape[2] == 3:
        # Balanceamento de branco melhorado
        if white_balance:
            lab = cv2.cvtColor(processed_uint8, cv2.COLOR_BGR2LAB)
            l, a, b = cv2.split(lab)

            # Garantir que os canais são do tipo correto e contíguos
            l = np.ascontiguousarray(l, dtype=np.uint8)
            a = np.ascontiguousarray(a, dtype=np.uint8)
            b = np.ascontiguousarray(b, dtype=np.uint8)

            avg_a = np.mean(a)
            avg_b = np.mean(b)

            # Aplicar correção com clipping para evitar underflow/overflow
            a_corrected = np.clip(a - (avg_a - 128), 0, 255).astype(np.uint8)
            b_corrected = np.clip(b - (avg_b - 128), 0, 255).astype(np.uint8)

            # Verificar dimensões antes do merge
            if l.shape == a_corrected.shape == b_corrected.shape:
                lab = cv2.merge([l, a_corrected, b_corrected])
                processed_uint8 = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)
                processed = img_as_float(processed_uint8)
            else:
                print("Aviso: Dimensões dos canais LAB não coincidem - pulando balanceamento de branco")

        # Ajuste de saturação (apenas se fator ≠ 1)
        if saturation_factor != 1.0:
            hsv = cv2.cvtColor(processed_uint8, cv2.COLOR_BGR2HSV).astype(np.float32)
            hsv[:, :, 1] = np.clip(hsv[:, :, 1] * saturation_factor, 0, 255)
            processed_uint8 = cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)
            processed = img_as_float(processed_uint8)

        # Ajuste de contraste (apenas se alpha ≠ 1 ou beta ≠ 0)
        if contrast_alpha != 1.0 or contrast_beta != 0:
            processed_uint8 = cv2.convertScaleAbs(processed_uint8, alpha=contrast_alpha, beta=contrast_beta)
            processed = img_as_float(processed_uint8)
    else:
        # Para imagens P&B, apenas ajuste de contraste
        if contrast_alpha != 1.0 or contrast_beta != 0:
            processed_uint8 = cv2.convertScaleAbs(processed_uint8, alpha=contrast_alpha, beta=contrast_beta)
            processed = img_as_float(processed_uint8)

    plot_comparison(img, processed, 'Correção de Cor')
    return processed

def postprocess_image(img, upscale_factor=1, denoise_sigma=0):

    processed = img.copy()

    # Converter para uint8 se necessário
    if processed.max() <= 1.0:
        processed_uint8 = (processed * 255).clip(0, 255).astype(np.uint8)
    else:
        processed_uint8 = processed.astype(np.uint8)

    # Upscaling (apenas se fator > 1)
    if upscale_factor > 1:
        h, w = processed.shape[:2]
        new_size = (int(w * upscale_factor), int(h * upscale_factor))
        processed_uint8 = cv2.resize(processed_uint8, new_size, interpolation=cv2.INTER_CUBIC)

    # Denoising (apenas se sigma > 0)
    if denoise_sigma > 0:
        if len(processed.shape) == 3:
            processed_uint8 = cv2.fastNlMeansDenoisingColored(processed_uint8, None, denoise_sigma, denoise_sigma, 7, 21)
        else:
            processed_uint8 = cv2.fastNlMeansDenoising(processed_uint8, None, denoise_sigma, 7, 21)

    processed = img_as_float(processed_uint8)
    plot_comparison(img, processed, 'Pós-processamento')
    return processed

def restore_image(img_path, pipeline_functions, target_size=None):
    # Carregar imagem
    img = cv2.imread(img_path)
    if img is None:
        raise ValueError(f"Não foi possível carregar a imagem em {img_path}")

    # Converter para float32 e normalizar para [0, 1]
    img = img_as_float(img)

    # Aplicar pipeline
    processed = img.copy()
    for func in pipeline_functions:
        processed = func(processed)

    return processed

"""# Execuções e Métodos Individuais

## k.jpg

### Execução
"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'k.jpg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                         bilateral_d=9,  # Apenas bilateral
                                         median_k=0,     # Mediano desligado
                                         inpaint_radius=0,  # Inpainting desligado
                                         fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        # lambda x: color_correction(x,
        #                             white_balance=True,
        #                             saturation_factor=1.5,
        #                             contrast_alpha=1.0,
        #                             contrast_beta=0),
        lambda x: postprocess_image(x,
                                    upscale_factor=1,
                                    denoise_sigma=5)
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Exibição Final"""

img_inicial = cv2.imread('k.jpg')
img_final = cv2.imread('k_restored.jpg')
img_final = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)  # Converter para RGB')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_final)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_06.jpg

### Remoções e Consertos
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('old_photo_06.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Ajuste refinado: área exata do rasgo
x1, x2 = 340, 410
y1, y2 = 300, 370
recorte = img[y1:y2, x1:x2]

# Equalização de contraste
gray = cv2.cvtColor(recorte, cv2.COLOR_BGR2GRAY)
equalizado = cv2.equalizeHist(gray)
# Threshold mais sensível
_, mask = cv2.threshold(equalizado, 220, 255, cv2.THRESH_BINARY)

# Threshold com gray direto
# _, mask = cv2.threshold(gray, 180, 255, cv2.THRESH_BINARY)

# Fechamento para suavizar a máscara
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 7))
mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=1)

# Inpainting
corrigido = cv2.inpaint(recorte, mask, 3, cv2.INPAINT_TELEA)
img_corrigida = img.copy()
img_corrigida[y1:y2, x1:x2] = corrigido

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(cv2.cvtColor(recorte, cv2.COLOR_BGR2RGB))
plt.title('Recorte Original')

plt.subplot(1,3,2)
plt.imshow(mask, cmap='gray')
plt.title('Nova Máscara')

plt.subplot(1,3,3)
plt.imshow(cv2.cvtColor(corrigido, cv2.COLOR_BGR2RGB))
plt.title('Recorte Corrigido')

plt.show()

# Exibir a imagem com tamanho ajustado
plt.figure(figsize=(12, 12))

plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')  # Para remover os eixos

plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(img_corrigida, cv2.COLOR_BGR2RGB))
plt.title('Imagem Sem Rasgo')
plt.axis('off')  # Para remover os eixos

plt.show()

cv2.imwrite('old_photo_06_corrigida.jpg', img_corrigida)

"""### Execução"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_06_corrigida.jpg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                         bilateral_d=9,  # Apenas bilateral
                                         median_k=0,     # Mediano desligado
                                         inpaint_radius=0,  # Inpainting desligado
                                         fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        # lambda x: color_correction(x,
        #                             white_balance=True,
        #                             saturation_factor=1.5,
        #                             contrast_alpha=1.0,
        #                             contrast_beta=0),
        lambda x: postprocess_image(x,
                                    upscale_factor=1,
                                    denoise_sigma=5)
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Perspective Warping"""

# img = cv2.imread('old_photo_06_corrigida (1)_restored.jpg')
# img_rgb = cv2.cvtColor((img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB)

# img_rgb = cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB)

# Carregar a imagem restaurada
img = cv2.imread('old_photo_06_corrigida_restored.jpg')  # Nome gerado anteriormente
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Converter para RGB

# Exibir a imagem com tamanho ajustado
plt.figure(figsize=(10, 10))
plt.imshow(img_rgb)  # Exibe a imagem no formato RGB

# Configurar os eixos para mais detalhes
plt.axis('on')  # Habilita a exibição dos eixos

# Ajuste das subdivisões dos eixos (exemplo de subdivisão com 50 intervalos)
plt.xticks(range(0, img_rgb.shape[1], int(img_rgb.shape[1] / 10)))  # Eixo X
plt.yticks(range(0, img_rgb.shape[0], int(img_rgb.shape[0] / 10)))  # Eixo Y

# Habilitar a grade e personalizá-la
plt.grid(True, which='both', axis='both', color='gray', linestyle='--', linewidth=0.5)

# Exibir a imagem com as configurações dos eixos
plt.show()

# Cantos da imagem (antes)
frontCoverPtsBefore = np.array([[25, 25], [950, 10], [960, 1490], [20, 1520]], dtype="float32")

# Cantos da imagem (depois)
frontCoverPtsAfter = np.array([[0, 0], [920, 0], [920, 1450], [0, 1450]], dtype="float32")

# Obter as matrizes de transformação para a imagem
M_front = cv2.getPerspectiveTransform(frontCoverPtsBefore, frontCoverPtsAfter)

# Aplicar a transformação (perspectiva) na imagem
img_front = cv2.warpPerspective(img_rgb, M_front, (920, 1450)) # (200, 255) -> serão as dimensões da imagem transformada

# Exibir a imagem
plt.figure(figsize=(12, 12))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
# plt.imshow(img)
plt.title('Imagem Original')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_front)
plt.title('Imagem Transformada')

plt.show()

# cv2.imwrite('img_front.jpg', img_front)

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_06.jpg')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_front)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_07.jpg

### Execução
"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_07.jpg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                      bilateral_d=9,  # Apenas bilateral
                                      median_k=0,     # Mediano desligado
                                      inpaint_radius=0,  # Inpainting desligado
                                      fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        lambda x: color_correction(x,
                                white_balance=True,  # Apenas balanceamento
                                saturation_factor=1.0,  # Saturação neutra
                                contrast_alpha=1.0,  # Contraste neutro
                                contrast_beta=0),
        lambda x: postprocess_image(x,
                                  upscale_factor=1,     # Sem upscale
                                  denoise_sigma=5)      # Apenas denoise
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_07.jpg')
img_final = cv2.imread('old_photo_07_restored.jpg')
img_final = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)  # Converter para RGB')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_final)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_08.jpeg

### Execução
"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_08.jpeg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                         bilateral_d=9,  # Apenas bilateral
                                         median_k=0,     # Mediano desligado
                                         inpaint_radius=0,  # Inpainting desligado
                                         fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        # lambda x: color_correction(x,
        #                             white_balance=True,
        #                             saturation_factor=1.5,
        #                             contrast_alpha=1.0,
        #                             contrast_beta=0),
        lambda x: postprocess_image(x,
                                    upscale_factor=1,
                                    denoise_sigma=5)
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Perspective Warping"""

# img = cv2.imread('old_photo_06_corrigida (1)_restored.jpg')
# img_rgb = cv2.cvtColor((img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB)

# img_rgb = cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB)

# Carregar a imagem restaurada
img = cv2.imread('old_photo_08_restored.jpg')  # Nome gerado anteriormente
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Converter para RGB

# Exibir a imagem com tamanho ajustado
plt.figure(figsize=(10, 10))
plt.imshow(img_rgb)  # Exibe a imagem no formato RGB

# Configurar os eixos para mais detalhes
plt.axis('on')  # Habilita a exibição dos eixos

# Ajuste das subdivisões dos eixos (exemplo de subdivisão com 50 intervalos)
plt.xticks(range(0, img_rgb.shape[1], int(img_rgb.shape[1] / 10)))  # Eixo X
plt.yticks(range(0, img_rgb.shape[0], int(img_rgb.shape[0] / 10)))  # Eixo Y

# Habilitar a grade e personalizá-la
plt.grid(True, which='both', axis='both', color='gray', linestyle='--', linewidth=0.5)

# Exibir a imagem com as configurações dos eixos
plt.show()

# Cantos da imagem (antes)
frontCoverPtsBefore = np.array([[0, 65], [900, 35], [980, 1365], [0, 1365]], dtype="float32")

# Cantos da imagem (depois)
frontCoverPtsAfter = np.array([[0, 0], [950, 0], [950, 1365], [0, 1365]], dtype="float32")

# Obter as matrizes de transformação para a imagem
M_front = cv2.getPerspectiveTransform(frontCoverPtsBefore, frontCoverPtsAfter)

# Aplicar a transformação (perspectiva) na imagem
img_front = cv2.warpPerspective(img_rgb, M_front, (950, 1365)) # (200, 255) -> serão as dimensões da imagem transformada

# Exibir a imagem
plt.figure(figsize=(12, 12))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
# plt.imshow(img)
plt.title('Imagem Original')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_front)
plt.title('Imagem Transformada')

plt.show()

# cv2.imwrite('img_front.jpg', img_front)

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_08.jpeg')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_front)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_09.jpeg

### Remoções e Consertos
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# === PARÂMETROS AJUSTÁVEIS ===
kernel_size = 3     # Deve ser ímpar >= 3
alpha = 0.7         # Entre 0.0 (sem suavizar) e 1.0 (suavização total)

# ==============================

# Carrega imagem
img_original = cv2.imread('old_photo_09.jpeg')
img_corrigida_salt_pepper = img_original.copy()

# Lista de recortes (x1, x2, y1, y2)
areas_para_corrigir = [
    (140, 258, 175, 258),
    (20, 100, 200, 258),
    (0, 60, 0, 100),
    (150, 200, 0, 75),
]

# Aplicar filtro de mediana com mistura nas áreas definidas
for x1, x2, y1, y2 in areas_para_corrigir:
    recorte = img_corrigida_salt_pepper[y1:y2, x1:x2]
    recorte_median = cv2.medianBlur(recorte, kernel_size)
    recorte_denoised = cv2.addWeighted(recorte, 1 - alpha, recorte_median, alpha, 0)
    img_corrigida_salt_pepper[y1:y2, x1:x2] = recorte_denoised

# === SEGUNDA ETAPA: INPAINTING EM REGIÃO ESPECÍFICA ===

# Definir área do rasgo
x1, x2 = 150, 200
y1, y2 = 50, 200
recorte_rasgo = img_corrigida_salt_pepper[y1:y2, x1:x2]

# Equalização de contraste e criação de máscara
gray_rasgo = cv2.cvtColor(recorte_rasgo, cv2.COLOR_BGR2GRAY)
equalizado = cv2.equalizeHist(gray_rasgo)
_, mask = cv2.threshold(equalizado, 220, 255, cv2.THRESH_BINARY)

# Operação morfológica para suavizar a máscara
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 7))
mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=1)

# Aplicação de inpainting
recorte_corrigido = cv2.inpaint(recorte_rasgo, mask, 3, cv2.INPAINT_TELEA)

# Substituir área na imagem final
img_final = img_corrigida_salt_pepper.copy()
img_final[y1:y2, x1:x2] = recorte_corrigido

# === EXIBIÇÃO DOS RESULTADOS ===
plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(img_original, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(cv2.cvtColor(img_corrigida_salt_pepper, cv2.COLOR_BGR2RGB))
plt.title(f'Após Suavização (α={alpha})')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB))
plt.title('Final com Inpainting')
plt.axis('off')

plt.tight_layout()
plt.show()

cv2.imwrite('old_photo_09_corrigida.jpeg', img_final)

"""### Execução"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_09_corrigida.jpeg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                      bilateral_d=9,  # Apenas bilateral
                                      median_k=0,     # Mediano desligado
                                      inpaint_radius=0,  # Inpainting desligado
                                      fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        # lambda x: color_correction(x,
        #                         white_balance=True,  # Apenas balanceamento
        #                         saturation_factor=1.0,  # Saturação neutra
        #                         contrast_alpha=1.0,  # Contraste neutro
        #                         contrast_beta=0),
        lambda x: postprocess_image(x,
                                  upscale_factor=1,     # Sem upscale
                                  denoise_sigma=5)      # Apenas denoise
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Perspective Warping"""

# Carregar a imagem restaurada
img = cv2.imread('old_photo_09_corrigida_restored.jpg')  # Nome gerado anteriormente
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Converter para RGB

# Exibir a imagem com tamanho ajustado
plt.figure(figsize=(10, 10))
plt.imshow(img_rgb)  # Exibe a imagem no formato RGB

# Configurar os eixos para mais detalhes
plt.axis('on')  # Habilita a exibição dos eixos

# Ajuste das subdivisões dos eixos (exemplo de subdivisão com 50 intervalos)
plt.xticks(range(0, img_rgb.shape[1], int(img_rgb.shape[1] / 10)))  # Eixo X
plt.yticks(range(0, img_rgb.shape[0], int(img_rgb.shape[0] / 10)))  # Eixo Y

# Habilitar a grade e personalizá-la
plt.grid(True, which='both', axis='both', color='gray', linestyle='--', linewidth=0.5)

# Exibir a imagem com as configurações dos eixos
plt.show()

# Cantos da imagem (antes)
frontCoverPtsBefore = np.array([[25, 0], [1020, 0], [1020, 1360], [10, 1360]], dtype="float32")

# Cantos da imagem (depois)
frontCoverPtsAfter = np.array([[0, 0], [1020, 0], [1020, 1360], [0, 1360]], dtype="float32")

# Obter as matrizes de transformação para a imagem
M_front = cv2.getPerspectiveTransform(frontCoverPtsBefore, frontCoverPtsAfter)

# Aplicar a transformação (perspectiva) na imagem
img_front = cv2.warpPerspective(img_rgb, M_front, (1020, 1360)) # (200, 255) -> serão as dimensões da imagem transformada

# Exibir a imagem
plt.figure(figsize=(12, 12))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
# plt.imshow(img)
plt.title('Imagem Original')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_front)
plt.title('Imagem Transformada')

plt.show()

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_09.jpeg')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_front)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_10.jpg

### Execução
"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_10.jpg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                      bilateral_d=9,  # Apenas bilateral
                                      median_k=0,     # Mediano desligado
                                      inpaint_radius=0,  # Inpainting desligado
                                      fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        # lambda x: color_correction(x,
        #                         white_balance=True,  # Apenas balanceamento
        #                         saturation_factor=1.0,  # Saturação neutra
        #                         contrast_alpha=1.0,  # Contraste neutro
        #                         contrast_beta=0),
        lambda x: postprocess_image(x,
                                  upscale_factor=1,     # Sem upscale
                                  denoise_sigma=5)      # Apenas denoise
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_10.jpg')
img_final = cv2.imread('old_photo_10_restored.jpg')
img_final = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)  # Converter para RGB')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_final)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_14.jpeg

### Remoções e Consertos
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# === PARÂMETROS AJUSTÁVEIS ===
kernel_size = 5     # Deve ser ímpar >= 3
alpha = 0.5         # Entre 0.0 (sem suavizar) e 1.0 (suavização total)

# ==============================

# Carrega imagem
img = cv2.imread('old_photo_14.jpg')
img_corrigida = img.copy()

# Lista de recortes (x1, x2, y1, y2)
areas_para_corrigir = [
    (0, 395, 0, 395),
]

for x1, x2, y1, y2 in areas_para_corrigir:
    recorte = img[y1:y2, x1:x2]

    # Filtro de mediana
    recorte_median = cv2.medianBlur(recorte, kernel_size)

    # Mistura entre original e filtrado para suavização parcial
    recorte_denoised = cv2.addWeighted(recorte, 1 - alpha, recorte_median, alpha, 0)

    # Substituir recorte na imagem corrigida
    img_corrigida[y1:y2, x1:x2] = recorte_denoised

# Exibir resultados
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(img_corrigida, cv2.COLOR_BGR2RGB))
plt.title(f'Suavização com Mediana + Mistura (α={alpha})')
plt.axis('off')

plt.show()

cv2.imwrite('old_photo_14_corrigida.jpeg', img_final)

"""### Execução"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_14_corrigida.jpeg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        # lambda x: remove_noise_artifacts(x,
        #                               bilateral_d=9,  # Apenas bilateral
        #                               median_k=0,     # Mediano desligado
        #                               inpaint_radius=0,  # Inpainting desligado
        #                               fft_threshold=0),  # FFT desligado
        # lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        # lambda x: color_correction(x,
        #                         white_balance=True,  # Apenas balanceamento
        #                         saturation_factor=1.0,  # Saturação neutra
        #                         contrast_alpha=1.0,  # Contraste neutro
        #                         contrast_beta=0),
        lambda x: postprocess_image(x,
                                  upscale_factor=1,     # Sem upscale
                                  denoise_sigma=1)      # Apenas denoise
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Perspective Warping

### Exibição Final
"""

img_inicial = cv2.imread('old_photo_14.jpg')
img_final = cv2.imread('old_photo_14_corrigida_restored.jpg')
img_final = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)  # Converter para RGB')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_final)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_18.jpg

### Execução
"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_18.jpg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                      bilateral_d=9,  # Apenas bilateral
                                      median_k=0,     # Mediano desligado
                                      inpaint_radius=0,  # Inpainting desligado
                                      fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        lambda x: color_correction(x,
                                white_balance=True,  # Apenas balanceamento
                                saturation_factor=1.0,  # Saturação neutra
                                contrast_alpha=1.0,  # Contraste neutro
                                contrast_beta=0),
        lambda x: postprocess_image(x,
                                  upscale_factor=1,     # Sem upscale
                                  denoise_sigma=5)      # Apenas denoise
    ]

    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_18.jpg')
img_final = cv2.imread('old_photo_18_restored.jpg')
img_final = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)  # Converter para RGB')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_final)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_19.jpg

### Execução
"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_19.jpg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                      bilateral_d=9,  # Apenas bilateral
                                      median_k=0,     # Mediano desligado
                                      inpaint_radius=0,  # Inpainting desligado
                                      fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        # lambda x: color_correction(x,
        #                         white_balance=True,  # Apenas balanceamento
        #                         saturation_factor=1.0,  # Saturação neutra
        #                         contrast_alpha=1.0,  # Contraste neutro
        #                         contrast_beta=0),
        lambda x: postprocess_image(x,
                                  upscale_factor=1,     # Sem upscale
                                  denoise_sigma=5)      # Apenas denoise
    ]
    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_19.jpg')
img_final = cv2.imread('old_photo_19_restored.jpg')
img_final = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)  # Converter para RGB')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_final)
plt.title('Restaurada')
plt.axis('off')

"""## old_photo_22.jpg

### Execução
"""

if __name__ == "__main__":
    import cv2
    import os
    import numpy as np
    import matplotlib.pyplot as plt

    # Caminho da imagem já definido (não precisa mais do files.upload)
    img_path = 'old_photo_22.jpg'

    # Definir pipeline (comente as funções que não deseja usar)
    pipeline = [
        lambda x: preprocess_image(x, target_size=(1024, None), align=False),
        lambda x: remove_noise_artifacts(x,
                                      bilateral_d=9,  # Apenas bilateral
                                      median_k=0,     # Mediano desligado
                                      inpaint_radius=0,  # Inpainting desligado
                                      fft_threshold=0),  # FFT desligado
        lambda x: deblur_image(x, psf_type='circular', psf_size=5, wiener_balance=0.01),
        # lambda x: enhance_details(x, clahe_clip_limit=2.0, unsharp_amount=1.5),
        lambda x: color_correction(x,
                                white_balance=True,  # Apenas balanceamento
                                saturation_factor=1.0,  # Saturação neutra
                                contrast_alpha=1.0,  # Contraste neutro
                                contrast_beta=0),
        lambda x: postprocess_image(x,
                                  upscale_factor=1,     # Sem upscale
                                  denoise_sigma=5)      # Apenas denoise
    ]
    # Executar restauração
    restored_img = restore_image(img_path, pipeline)

    # Mostrar resultado final
    plt.figure(figsize=(15, 10))
    plt.subplot(1, 2, 1)
    original = cv2.imread(img_path)
    plt.imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
    plt.title('Original')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
    plt.title('Restaurada')
    plt.axis('off')

    plt.show()

    # Salvar resultado
    output_path = os.path.splitext(img_path)[0] + '_restored.jpg'
    cv2.imwrite(output_path, (restored_img * 255).astype(np.uint8))
    print(f"Imagem restaurada salva como {output_path}")

"""### Exibição Final"""

img_inicial = cv2.imread('old_photo_22.jpg')
img_final = cv2.imread('old_photo_22_restored.jpg')
img_final = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)  # Converter para RGB')

# Mostrar resultado final
plt.figure(figsize=(15, 10))
plt.subplot(1, 2, 1)
# original = cv2.imread(gray)
plt.imshow(cv2.cvtColor(img_inicial, cv2.COLOR_BGR2RGB))
plt.title('Imagem Original')
plt.axis('off')

plt.subplot(1, 2, 2)
# plt.imshow(cv2.cvtColor((restored_img * 255).astype(np.uint8), cv2.COLOR_BGR2RGB))
# plt.imshow(cv2.cvtColor(img_front, cv2.COLOR_BGR2RGB))
plt.imshow(img_final)
plt.title('Restaurada')
plt.axis('off')